Updates init.d script for bmserver.

diff --git a/scripts/bmserver b/scripts/bmserver
--- a/scripts/bmserver
+++ b/scripts/bmserver
@@ -7,17 +7,16 @@
 . /etc/rc.d/init.d/functions
 
 USER="ec2-user" # can we run as nobody?
-
-SERVER="/home/ec2-user/bmserver.py"
+SERVER="/usr/bin/python /home/ec2-user/bmserver.py"
 LOG_FILE="/home/ec2-user/bmserver.log"
-
 LOCK_FILE="/var/lock/subsys/bmserver"
 
 do_start()
 {
         if [ ! -f "$LOCK_FILE" ] ; then
                 echo -n $"Starting $SERVER: "
-                runuser -l "$USER" -c $DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
+                # TODO: find out why python's stdout isn't being redirected to log file
+                runuser -l "$USER" -c "$DAEMON $SERVER >> $LOG_FILE 2>&1 &" && echo_success || echo_failure
                 RETVAL=$?
                 echo
                 [ $RETVAL -eq 0 ] && touch $LOCK_FILE
